# Generated by Django 3.2.4 on 2021-07-25 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant_app', '0003_alter_orderhistory_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
