# Generated by Django 3.2.4 on 2021-07-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant_app', '0004_alter_orderhistory_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
